apiVersion: v1
kind: Service
metadata:
  name: voyage-api-service
spec:
  selector:
    app: voyage-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP  # Internal networking only (UI talks to this)