apiVersion: v1
kind: Service
metadata:
  name: voyage-ui-service
spec:
  selector:
    app: voyage-ui
  ports:
    - protocol: TCP
      port: 80        # Standard web port exposed to the user
      targetPort: 8501 # Internal container port
  type: LoadBalancer  # Opens this up to the outside world